In [32]:
from scipy.fftpack import dct, idct
import numpy as np

In [36]:
input_data = np.array([-1.0, -2.0, -1.0, 0.0, 1.0, 2.0, 1.0, 0.0], dtype=float)
input_data = input_data + 2.0
input_data

array([1., 0., 1., 2., 3., 4., 3., 2.])

## norm = None

In [37]:
dcted = dct(input_data)
dcted

array([ 32.        , -10.67399028,  -5.22625186,   6.50345486,
         0.        ,   1.94009006,   2.1647844 ,  -0.08400636])

In [38]:
idct(dcted)

array([ 1.60000000e+01, -7.10542736e-15,  1.60000000e+01,  3.20000000e+01,
        4.80000000e+01,  6.40000000e+01,  4.80000000e+01,  3.20000000e+01])

## norm = 'ortho'

In [39]:
dcted = dct(input_data, norm='ortho')
dcted

array([ 5.65685425, -2.66849757, -1.30656296,  1.62586371,  0.        ,
        0.48502251,  0.5411961 , -0.02100159])

In [40]:
idct(dcted, norm='ortho')

array([1., 0., 1., 2., 3., 4., 3., 2.])